- name: Add local machine to inventory
  hosts: all
  connection: local
  gather_facts: False
  tasks:
  - add_host:
      name: 127.0.0.1
      
- name: Create new server
  hosts:
  - 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  - local_action:
      count: 1
      module: ec2
      keypair: likwid
      group:
      - likwid-web-servers
      instance_tags: '{"Demo":"Demo"}'
      instance_type: c1.xlarge
      image: ami-d3c986ba
      region: us-east-1
      wait: true
    register: ec2
    
  - name: Add new instance to host group
    local_action: add_host hostname={{ item.public_dns_name }} groupname=launched
    with_items: ec2.instances
  
  - name: Wait for SSH to come up
    local_action: wait_for host={{ item.public_dns_name }} port=22 delay=10 timeout=320 state=started
    with_items: ec2.instances

- hosts: launched
  vars:
    app: sample
    user: ubuntu
    group: www-data
    sudo: true

  roles:
  - common
  - ruby-2.0.0
  - web

  handlers:
  - name: reload nginx
    action: service name=nginx state=reloaded
    sudo: yes
    
  - name: restart monit
    action: service name=monit state=restarted
    sudo: yes

